name: Docker Image CVE scanner
on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:
jobs:
  scan_jvm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['latest', '3.7.0']
    steps:
      - name: Run CVE scan
        uses: aquasecurity/trivy-action@master
        if: always()
        with:
          image-ref: apache/kafka:${{ matrix.tag }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          output: scan_report_jvm_${{ matrix.tag }}.txt
          exit-code: '1'
      - name: Upload CVE scan report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: scan_report_jvm_${{ matrix.tag }}.txt
          path: scan_report_jvm_${{ matrix.tag }}.txt
