name: Docker Image CVE scanner
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  scan_jvm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['latest', '3.6.0-release', '3.6.0-release-actions']
    steps:
      - name: Run CVE scan
        uses: aquasecurity/trivy-action@master
        if: always()
        with:
          image-ref: vedarthconfluent/vedarth-kafka-test:${{ matrix.tag }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          output: scan_report_jvm_${{ matrix.tag }}.txt
          exit-code: '1'
      - name: Upload CVE scan report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: scan_report_jvm_${{ matrix.tag }}.txt
          path: scan_report_jvm_${{ matrix.tag }}.txt
