name: Docker build test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/test/requirements.txt
    - name: Test with pytest
      run: |
        python docker_build_test.py kafka/test -tag=classpath -type=jvm -u=https://downloads.apache.org/kafka/3.6.0/kafka_2.13-3.6.0.tgz
