name: Docker build test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/test/requirements.txt
    - name: Run tests
      working-directory: ./docker
      run: |
        python docker_build_test.py kafka/test -tag=3.6.0 -type=jvm -u=https://downloads.apache.org/kafka/3.6.0/kafka_2.13-3.6.0.tgz
    - name: Run Vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'kafka/test:3.6.0'
        format: 'table'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        output: scan.txt
    - uses: actions/upload-artifact@v3
      with:
        name: report.html
        path: docker/test/report.html
    - uses: actions/upload-artifact@v3
      with:
        name: scan.txt
        path: scan.txt